In [2]:
import cv2
import numpy as np
import glob
from tqdm import tqdm
import os

# 이미지 데이터셋이 있는 디렉토리 경로
dataset_dir1 = '/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/002_2022_인천신여객터미널/leftImg8bit/train'
dataset_dir2 = '/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/002_2022_인천신여객터미널/leftImg8bit/val'

# 이미지 파일 목록
image_files1 = [os.path.join(dataset_dir1, filename) for filename in os.listdir(dataset_dir1) if filename.endswith('_leftImg8bit.png')]
image_files2 = [os.path.join(dataset_dir2, filename) for filename in os.listdir(dataset_dir2) if filename.endswith('_leftImg8bit.png')]
image_files = image_files1 + image_files2

img_norm = list()
img_std = list()
for data in tqdm(image_files):
    img = cv2.imread(data, cv2.IMREAD_COLOR)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32)
    if len(img.shape) <2: # 흑백 이미지는 제외
        continue
    mean,std = np.mean(img, axis=(0,1)), np.std(img, axis=(0,1))
    img_norm.append(mean)
    img_std.append(std)

print(np.mean(img_norm, axis=0), np.mean(img_std, axis=0))

100%|██████████| 598/598 [03:06<00:00,  3.21it/s]

[138.14046 137.48306 131.4548 ] [44.734947 42.97031  43.756325]


In [3]:
# 이미지 데이터셋이 있는 디렉토리 경로
dataset_dir1 = '/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/leftImg8bit/train'
dataset_dir2 = '/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/leftImg8bit/val'

# 이미지 파일 목록
image_files1 = [os.path.join(dataset_dir1, filename) for filename in os.listdir(dataset_dir1) if filename.startswith('Rissbilder') or filename.startswith('noncrack')]
image_files2 = [os.path.join(dataset_dir2, filename) for filename in os.listdir(dataset_dir2) if filename.startswith('Rissbilder')]
image_files = image_files1 + image_files2

# 이미지 데이터를 저장할 리스트
image_data = []

# 이미지 파일을 읽어와서 리스트에 추가
for image_file in image_files:
    image = cv2.imread(image_file)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # 이미지를 RGB 형식으로 변환
    image_data.append(image)

# 이미지 데이터를 NumPy 배열로 변환
image_data = np.array(image_data)

# 각 채널(예: RGB)에 대한 평균과 표준 편차 계산
mean = np.mean(image_data, axis=(0, 1, 2))
std = np.std(image_data, axis=(0, 1, 2))

# 결과 출력
print("평균(Mean):", mean)
print("표준 편차(Standard Deviation):", std)

평균(Mean): [120.11962108 130.6978745  137.02111115]
표준 편차(Standard Deviation): [39.03891851 34.82510309 34.42971648]


In [12]:
len(image_files)

206

In [47]:
image.shape

(3024, 4032, 3)

In [29]:
# check etc

tmp = np.load('pixel_counts/deepcrack_target_pixel_counts.npy')
tmp

array([[1023318,   25258],
       [ 986582,   61994],
       [1012199,   36377],
       ...,
       [ 958043,   90533],
       [ 956299,   92277],
       [ 878601,  169975]])

In [30]:
PER_TH = 0.1
num_class = 2

m = np.zeros(num_class)

In [31]:
for i in range(10):
        counts = [tmp[tmp[:, i] > PER_TH*m[i], i] for i in range(num_class)]
        m = [np.mean(c) for c in counts]

In [32]:
m

[1011031.7619961612, 37744.69305019305]

In [33]:
np.zeros(num_class)

array([0., 0.])

In [35]:
np.mean(tmp, axis=0)

array([1011031.76199616,   37544.23800384])

In [36]:
lbl = np.zeros((512, 512), dtype=int)
lbl

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
np.sum(lbl == 1)

0

In [ ]:
[np.sum(lbl == i) > PER_TH * counts[i] for i in range(num_class)]

In [39]:
512*512

262144