In [14]:
# 하위 폴더 있을 때

import os
import numpy as np
from PIL import Image
from tqdm import tqdm

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/002_2022_인천신여객터미널/gtFine'

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

# 각 하위 폴더에서 이미지 처리
noncrack_num = 0
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # PNG 파일만 선택
    png_files = [f for f in file_list if f.endswith('_gtFine_labelIds.png')]

    # 클래스별 픽셀 개수 계산 및 저장
    for png_file in tqdm(png_files):
        # 이미지 열기
        image = Image.open(os.path.join(subfolder_path, png_file))

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        if not np.array_equal(np.unique(img_array), np.array([0, 1])):
            # print(os.path.join(subfolder_path, png_file))
            # print(np.unique(img_array))
            if np.array_equal(np.unique(img_array), np.array([0])):
                noncrack_num += 1

print('noncrack num: ', noncrack_num)

100%|██████████| 48/48 [00:03<00:00, 13.80it/s]

noncrack num:  295


In [58]:
img_array.shape

(448, 448)

In [1]:
# 하위 폴더 없을 때

import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/gtFine/train'

# 각 폴더 내의 모든 파일 리스트 가져오기
file_list = os.listdir(parent_folder)

# 파일 선택
png_files = [f for f in file_list if f.startswith('Rissbilder')]

crack = 0
noncrack = 0

# 클래스별 픽셀 개수 계산
for png_file in png_files:
    # 이미지 열기
    image = Image.open(os.path.join(parent_folder, png_file))

    # 이미지를 NumPy 배열로 변환
    img_array = np.array(image)

    if np.array_equal(np.unique(img_array), np.array([0, 1])):
        crack += 1
    elif np.array_equal(np.unique(img_array), np.array([0])):
        noncrack += 1
        # print(os.path.join(parent_folder, png_file))
        # print(np.unique(img_array))

print(crack)
print(noncrack)

2174
15


In [20]:
# 원소 값 변경 (하위 폴더 있을 때)

import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/23. KaggleCrack/03. Cityscapes Dataset/gtFine'
output_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/23. KaggleCrack/03. Cityscapes Dataset/modified_gtFine'

# 클래스별 픽셀 개수를 저장할 빈 NumPy 배열 생성
class_pixel_counts = []

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

# 각 하위 폴더에서 이미지 처리
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # PNG 파일만 선택
    png_files = [f for f in file_list if f.endswith('_gtFine_labelIds.png')]

    # 클래스별 픽셀 개수 계산 및 저장
    for png_file in png_files:
        # 이미지 열기
        image = Image.open(os.path.join(subfolder_path, png_file))

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        # NumPy 배열 내에서 2의 값을 가지는 픽셀을 1로 변경
        img_array[img_array == 2] = 1

        # 변경된 NumPy 배열을 이미지로 변환
        modified_image = Image.fromarray(img_array)

        # 이미지를 PNG 파일로 저장
        modified_image.save(os.path.join(output_folder, subfolder, png_file))
        

In [52]:
# 원소 값 변경 (하위 폴더 없을 때)

import os
import numpy as np
from PIL import Image
from tqdm import tqdm

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/01. Original Data Downloaded from GitHub Repo/val/masks'
modified_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/gtFine/val'

# 각 폴더 내의 모든 파일 리스트 가져오기
file_list = os.listdir(parent_folder)

# 파일 선택
png_files = [f for f in file_list if f.endswith('.jpg')]

# 클래스별 픽셀 개수 계산 및 저장
for png_file in tqdm(png_files):
    # 이미지 열기
    image = Image.open(os.path.join(parent_folder, png_file))

    # 이미지를 NumPy 배열로 변환
    img_array = np.array(image) / 255

    modified_array = np.where(img_array < 0.3, 0, 1).astype(np.uint8)

    modified_img = Image.fromarray(modified_array)

    file_name = png_file.replace('.jpg', '_gtFine_labelIds.png')

    modified_img.save(os.path.join(modified_folder, file_name))

100%|██████████| 1695/1695 [00:29<00:00, 56.64it/s]


In [49]:
# 확장자만 변경

import os
import shutil
from tqdm import tqdm

# 원본 이미지 파일이 있는 폴더 경로
source_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/01. Original Data Downloaded from GitHub Repo/train/images"

# 변경된 이미지 파일을 저장할 폴더 경로
destination_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/leftImg8bit/train"

# 변경할 확장자
new_extension = "_leftImg8bit.png"  # 새 확장자로 변경

# 원본 폴더 내의 모든 파일 목록 가져오기
file_list = os.listdir(source_folder)

# 이미지 파일 필터링 및 확장자 변경 및 저장
for filename in tqdm(file_list):
    if filename.lower().endswith(".jpg"):
        # 이미지 파일인 경우에만 처리
        old_path = os.path.join(source_folder, filename)
        new_filename = os.path.splitext(filename)[0] + new_extension  # 확장자 변경
        new_path = os.path.join(destination_folder, new_filename)
        
        # 이미지 파일을 목적 폴더로 복사
        shutil.copy(old_path, new_path)

100%|██████████| 1304/1304 [00:13<00:00, 95.42it/s] 


In [25]:
import shutil

# 원본 이미지 파일이 있는 폴더 경로
source_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/leftImg8bit"

# 대상 train 및 val 폴더 경로
train_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/leftImg8bit/train"
val_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/leftImg8bit/val"

# train 폴더 생성
if not os.path.exists(train_folder):
    os.mkdir(train_folder)

# val 폴더 생성
if not os.path.exists(val_folder):
    os.mkdir(val_folder)

# train.txt 파일과 val.txt 파일 경로
train_txt = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/Final_Dataset/train.txt"
val_txt = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/Final_Dataset/test.txt"

# train.txt 파일 처리
with open(train_txt, "r") as train_file:
    train_files = train_file.read().splitlines()

for filename in train_files:
    filename = filename.replace(".png", "_leftImg8bit.png")
    source_path = os.path.join(source_folder, filename)
    dest_path = os.path.join(train_folder, filename)
    if os.path.exists(source_path):
        shutil.move(source_path, dest_path)

# val.txt 파일 처리
with open(val_txt, "r") as val_file:
    val_files = val_file.read().splitlines()

for filename in val_files:
    filename = filename.replace(".png", "_leftImg8bit.png")
    source_path = os.path.join(source_folder, filename)
    dest_path = os.path.join(val_folder, filename)
    if os.path.exists(source_path):
        shutil.move(source_path, dest_path)

In [35]:
import shutil

# 원본 이미지 파일이 있는 폴더 경로
source_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/gtFine"

# 대상 train 및 val 폴더 경로
train_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/gtFine/train"
val_folder = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/convert2cityscapes/gtFine/val"

# train 폴더 생성
if not os.path.exists(train_folder):
    os.mkdir(train_folder)

# val 폴더 생성
if not os.path.exists(val_folder):
    os.mkdir(val_folder)

# train.txt 파일과 val.txt 파일 경로
train_txt = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/Final_Dataset/train.txt"
val_txt = "/home/user/WindowsShare/05. Data/00. Benchmarks/27. crackseg9k/Final_Dataset/test.txt"

# train.txt 파일 처리
with open(train_txt, "r") as train_file:
    train_files = train_file.read().splitlines()

for filename in train_files:
    filename = filename.replace('.png', '_gtFine_labelIds.png')
    source_path = os.path.join(source_folder, filename)
    dest_path = os.path.join(train_folder, filename)
    if os.path.exists(source_path):
        shutil.move(source_path, dest_path)

# val.txt 파일 처리
with open(val_txt, "r") as val_file:
    val_files = val_file.read().splitlines()

for filename in val_files:
    filename = filename.replace('.png', '_gtFine_labelIds.png')
    source_path = os.path.join(source_folder, filename)
    dest_path = os.path.join(val_folder, filename)
    if os.path.exists(source_path):
        shutil.move(source_path, dest_path)

In [6]:
# 이미지 1장 확인

import numpy as np
from PIL import Image

image = Image.open("/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/001_2021_물양장&도로공사&균열Negative/gtFine/train/DSCN0057 029__0,3072)__gtFine_labelIds.png")
img_array = np.array(image)

np.unique(img_array)

array([0, 1, 3], dtype=uint8)

In [7]:
img_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
# 손상 없는 이미지 gt 생성

from PIL import Image
import os
import numpy as np
from tqdm import tqdm

input_folder = "/home/user/no_damage"
output_folder = "/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/002_2022_인천신여객터미널"

for filename in tqdm(os.listdir(input_folder)):
    if filename.endswith(".png"):
        img_path = os.path.join(input_folder, filename)
        img = Image.open(img_path)

        new_filename_img = filename.replace('.png', '_leftImg8bit.png')
        output_path_img = os.path.join(output_folder, 'leftImg8bit', 'train', new_filename_img)
        img.save(output_path_img)

        gt = np.zeros((np.array(img).shape[0], np.array(img).shape[1]), dtype=np.uint8)
        gt = Image.fromarray(gt)
        new_filename_gt = new_filename_img.replace('_leftImg8bit.png', '_gtFine_labelIds.png')
        output_path_gt = os.path.join(output_folder, 'gtFine', 'train', new_filename_gt)
        gt.save(output_path_gt)

100%|██████████| 294/294 [06:12<00:00,  1.27s/it]


In [8]:
np.array(img).shape[0]

2048

In [11]:
np.zeros((2048, 2048))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])