In [7]:
# read .npy file

import numpy as np

data = np.load('pixel_counts/crack500_s_pixel_counts.npy')

print(data.shape)
print(data)

(1785, 2)
[[158480   1520]
 [159271    729]
 [147941  12059]
 ...
 [159440    560]
 [158820   1180]
 [154663   5337]]


In [7]:
import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/02. Training&Test/022. Ministry of Ocean/003_2022_강화도어항/gtFine'

# 클래스별 픽셀 개수를 저장할 빈 NumPy 배열 생성
class_pixel_counts = []

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

# 각 하위 폴더에서 이미지 처리
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # PNG 파일만 선택
    png_files = [f for f in file_list if f.endswith('.png')]
    print(len(png_files))

    # 클래스별 픽셀 개수 계산 및 저장
    for png_file in png_files:
        # 이미지 열기
        image = Image.open(os.path.join(subfolder_path, png_file))

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        # 각 클래스별 픽셀 개수 세기
        class_pixel_count = np.bincount(img_array.ravel(), minlength=4)  # 256은 픽셀 값 범위 (0-255)

        # 클래스별 픽셀 개수를 class_pixel_counts에 추가
        class_pixel_counts.append(class_pixel_count)

# class_pixel_counts를 NumPy 배열로 변환
result_array = np.array(class_pixel_counts)

# 결과를 .npy 파일로 저장
# np.save('pixel_counts/cfd_target_pixel_counts.npy', result_array)

640
40


In [8]:
result_array.shape

(680, 4)

In [9]:
result_array

array([[4193705,     599,       0,       0],
       [4193656,     648,       0,       0],
       [4098179,    4235,       0,   91890],
       ...,
       [1812662,       0,  115573, 2266069],
       [2403230,       0,  130477, 1660597],
       [1917953,       0,  133509, 2142842]])

In [11]:
np.save('pixel_counts/ganghwa_t_pixel_counts.npy', result_array)

In [13]:
import os
import numpy as np
from PIL import Image

# 상위 폴더 경로 설정
parent_folder = '/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/leftImg8bit'

# 클래스별 픽셀 개수를 저장할 빈 NumPy 배열 생성
class_pixel_counts = []

# 상위 폴더 내의 모든 하위 폴더 리스트 가져오기
subfolders = [f for f in os.listdir(parent_folder) if os.path.isdir(os.path.join(parent_folder, f))]

# 각 하위 폴더에서 이미지 처리
for subfolder in subfolders:
    subfolder_path = os.path.join(parent_folder, subfolder)

    # 각 폴더 내의 모든 파일 리스트 가져오기
    file_list = os.listdir(subfolder_path)

    # 파일 선택
    png_files = [f for f in file_list if f.startswith('cracktree200')]
    print(len(png_files))

    subfolder_path = subfolder_path.replace('leftImg8bit', 'gtFine')
    print(subfolder_path)

    # 클래스별 픽셀 개수 계산 및 저장
    for png_file in png_files:
        # 이미지 열기
        png_file = png_file.replace('_leftImg8bit.png', '_gtFine_labelIds.png')
        image = Image.open(os.path.join(subfolder_path, png_file))

        # 이미지를 NumPy 배열로 변환
        img_array = np.array(image)

        # 각 클래스별 픽셀 개수 세기
        class_pixel_count = np.bincount(img_array.ravel(), minlength=2)  # 256은 픽셀 값 범위 (0-255)

        # 클래스별 픽셀 개수를 class_pixel_counts에 추가
        class_pixel_counts.append(class_pixel_count)

# class_pixel_counts를 NumPy 배열로 변환
result_array = np.array(class_pixel_counts)

175
/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/gtFine/train
31
/home/user/WindowsShare/05. Data/00. Benchmarks/22. KhanhhaCrack/04. convert2cityscapes/gtFine/val


In [14]:
result_array.shape

(206, 2)

In [16]:
np.save('pixel_counts/cracktree200_s_pixel_counts.npy', result_array)

In [20]:
tmp = np.load('pixel_counts/gaps_s_pixel_counts.npy')
tmp

array([[198309,   2395],
       [196017,   4687],
       [196921,   3783],
       ...,
       [194566,   6138],
       [199332,   1372],
       [198806,   1898]])

In [21]:
tmp.shape

(509, 2)

In [24]:
m = np.zeros(2)
m

array([0., 0.])

In [23]:
PER_TH = 0.1

In [25]:
for i in range(10):
    counts = [tmp[tmp[:, i] > PER_TH*m[i], i] for i in range(2)]
    m = [np.mean(c) for c in counts]
m

[198267.7033398821, 2436.296660117878]

In [30]:
tmp

array([[198309,   2395],
       [196017,   4687],
       [196921,   3783],
       ...,
       [194566,   6138],
       [199332,   1372],
       [198806,   1898]])

In [31]:
np.mean(tmp, axis=0)

array([198267.70333988,   2436.29666012])